name: Sync from Upstream

permissions:
  contents: write # 允许写入代码到你的仓库

on:
  schedule:
    - cron: '*/40 * * * *' # 每30分钟检查一次 (你可以根据需求调整)
  workflow_dispatch:       # 允许手动点击按钮触发同步

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    steps:
    - name: Checkout target repo
      uses: actions/checkout@v4

    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      with:
        upstream_sync_repo: Picarran/cooking-learning-backend # 原作者仓库
        upstream_sync_branch: main
        target_sync_branch: main
        target_repo_token: ${{ secrets.DEPLOYMENT_TOKEN }} # 自动生成的token，无需配置

    - name: Show sync status
      if: steps.sync.outputs.has_new_commits == 'true'
      run: echo "New commits were found to sync."
